### ISSUE TITLE
Adding multiple chords in one `chord` object

### ISSUE THREAD

**Issue by mzacho** [emicklei/melrose#10]
When sending `play(chord('1e/m7 1f#/m7'))` to the interpreter, I receive

```
{
	"type": "core.Chord",
	"is-error": false,
	"stoppable": false,
	"message": "chord('1E/m/7')",
	"file": "foo",
	"line": 1,
	"column": 0,
	"object": null
}
```
i.e., the f#/m7 is completely ignored.

I'd suspect the program to either return an error message or play both chords

**Comment by emicklei** [comment]
this has been fixed on Aug 28, I will close this
