### ISSUE TITLE
Errornous version update info

### ISSUE THREAD

**Issue by mzacho** [emicklei/melrose#9]
After installing the latest .pkg of Melrose available for MacOS and running `melrose --help`, expecting to see some sort of CLI help message, I'm informed that there's a newer version of Melrose available:

```
mzacho@hostname$ melrose --help
you are running version v0.43.0, a newer version (v0.40.0) is available on http://melrōse.org
melrōse - program your melodies - v0.43.0
𝄞
```

Two things surprise me:
- `melrose` informs me that there's a newer version (v0.40.0) than my current v0.43.0 available
- `melrose` ignores my --help option

**Comment by mzacho** [comment]
Followup:

`melrose` also seems to be a bit stubborn when it comes to exiting the program: The usual `^C` or `^D` doesn't work:

```
𝄞 ^C
error: prompt aborted
𝄞 error: EOF
```

And none of `help`, `exit`, `stop`, `quit` or `?` are recognised by the interpreter:

```
𝄞 help
error: unknown name help (1:1)
 | help
 | ^
𝄞 exit
error: unknown name exit (1:1)
 | exit
 | ^
𝄞 stop
0x4392940 type:func(...dsl.variable) interface {}
𝄞 quit
error: unknown name quit (1:1)
 | quit
 | ^
𝄞 ?
error: unexpected token Operator("?") (1:1)
 | ?
 | ^
```

I'd expect that `melrose` would print out some helpful message before starting the interpreter, to inform me how to quit the program.

**Comment by emicklei** [comment]
thank you reporting these issues. I will address them soon.

**Comment by emicklei** [comment]
btw, the reason for not interpreting the commands "help, exit, etc" is that these are allowed as variables in the language. So to escape this, you need the prefix command with ":".  I will add a line on startup to explain this short. Thanks for the feedback.

**Comment by emicklei** [comment]
I have update the tool (v0.46.0) that includes fixes for "ctrl+c" and temporary disabled the version check.
You can find a new release here

**Comment by mzacho** [comment]
Happy to help out, I think the tool has potential - I've started porting your VSCode extension to Emacs [https://www.github.com/mzacho/melrose-for-emacs](https://www.github.com/mzacho/melrose-for-emacs)
